import express from 'express';
import { reportIssue, getMyIssues, getSectorIssues, addComment  } from '../controllers/issueController.js';
import authCitizen from '../middleware/authCitizen.js';
import authSectorHead from '../middleware/authSectorHead.js';
import { forceCloseIssue } from '../controllers/issueController.js';
import { exportIssues } from '../controllers/issueController.js';
import { protect } from '../middleware/auth.js';
import { getCitizenIssues } from '../controllers/issueController.js';
import { updateIssueStatus } from '../controllers/issueController.js';

const router = express.Router(); 
router.put('https://civicconnect-1f9p.onrender.com/:id/status', authSectorHead, updateIssueStatus);
router.post('https://civicconnect-1f9p.onrender.com/:id/comment', authSectorHead, addComment);
router.post('https://civicconnect-1f9p.onrender.com/report', authCitizen, reportIssue);
router.get('https://civicconnect-1f9p.onrender.com/my', authCitizen, getMyIssues);
router.get('https://civicconnect-1f9p.onrender.com/sector', authSectorHead, getSectorIssues);
router.put('https://civicconnect-1f9p.onrender.com/:id/close', authSectorHead, forceCloseIssue);
router.get('https://civicconnect-1f9p.onrender.com/export-issues', protect, exportIssues);
router.get('https://civicconnect-1f9p.onrender.com/issue-status', protect, getCitizenIssues);
export default router;
